name: ci

on:
  push:
    branches:
    - "moonpay-task"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set short sha
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 839991594784.dkr.ecr.eu-west-1.amazonaws.com/nestjs-realworld-example-app:${{ env.SHORT_SHA }}
        build-args: |
            SHORT_SHA=${{ env.SHORT_SHA }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_FILE }}
        with:
          command: helm upgrade nestjs-realworld-example-app --install --wait ./chart --set image.tag=$(echo ${GITHUB_SHA} | cut -c1-8)